model_name: NousResearch/Hermes-2-Pro-Llama-3-8B
steering_vector_path: /workspace/SteerPoser/src/svec/safety
behavior_layer_ids: [15, 16, 17, 18, 19, 20, 21, 22, 23]
behavior_vector_strength: 1.2
max_new_tokens: 256
use_local: true
cache_dir: /workspace/.cache/huggingface