model_name: NousResearch/Hermes-2-Pro-Llama-3-8B
steering_vector_path: /home/aa-aanegola/SteerPoser/src/svec/safety.svec
behavior_layer_ids: [15, 16, 17, 18, 19, 20, 21, 22, 23]
behavior_vector_strength: 1.2
max_new_tokens: 256
use_local: false
cache_dir: ~/.cache/huggingface